FROM ubuntu

RUN apt-get update
RUN apt-get install -y mosquitto supervisor
COPY ./deployment/mosquitto.conf /etc/supervisor/conf.d/

EXPOSE 1883
ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/supervisord.conf"]

